// templates/tool-templates/new/vue-sample/src/components/ToolboxAPIDemo.vue
<template>
  <div class="card">
    <h2>🛠️ ToolBox API Examples</h2>

    <div class="example-group">
      <h3>Notifications</h3>
      <div class="button-group">
        <button
          @click="showNotification('Success!', 'Operation completed successfully', 'success')"
          class="btn btn-success"
        >
          Show Success
        </button>
        <button
          @click="showNotification('Information', 'This is an informational message', 'info')"
          class="btn btn-info"
        >
          Show Info
        </button>
        <button @click="showNotification('Warning', 'Please review this warning', 'warning')" class="btn btn-warning">
          Show Warning
        </button>
        <button @click="showNotification('Error', 'An error has occurred', 'error')" class="btn btn-error">
          Show Error
        </button>
        <button @click="showLoading" class="btn btn-primary">Show Loading</button>
      </div>
    </div>

    <div class="example-group">
      <h3>Utilities</h3>
      <div class="button-group">
        <button @click="copyToClipboard" class="btn">Copy to Clipboard</button>
        <button @click="showCurrentTheme" class="btn">Get Theme</button>
        <button @click="saveDataToFile" class="btn">Save File</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const emit = defineEmits<{
  log: [message: string, type?: "info" | "success" | "warning" | "error"];
}>();

const showNotification = async (title: string, body: string, type: "success" | "info" | "warning" | "error") => {
  try {
    await window.toolboxAPI.utils.showNotification({
      title,
      body,
      type,
      duration: 3000,
    });
    emit("log", `Notification shown: ${title} - ${body}`, type);
  } catch (error) {
    emit("log", `Error showing notification: ${(error as Error).message}`, "error");
  }
};

const showLoading = async () => {
  try {
    await window.toolboxAPI.utils.showLoading("Loading for 3 seconds please wait...");
    // Simulate some async operation
    setTimeout(async () => {
      await window.toolboxAPI.utils.hideLoading();
      emit("log", "Loading indicator hidden", "info");
    }, 3000);
  } catch (error) {
    emit("log", `Error showing loading indicator: ${(error as Error).message}`, "error");
  }
};

const copyToClipboard = async () => {
  try {
    const data = {
      timestamp: new Date().toISOString(),
      message: "This data was copied from the Vue Sample Tool",
    };

    await window.toolboxAPI.utils.copyToClipboard(JSON.stringify(data, null, 2));
    await showNotification("Copied!", "Data copied to clipboard", "success");
  } catch (error) {
    emit("log", `Error copying to clipboard: ${(error as Error).message}`, "error");
  }
};

const showCurrentTheme = async () => {
  try {
    const theme = await window.toolboxAPI.utils.getCurrentTheme();
    await showNotification("Current Theme", `The current theme is: ${theme}`, "info");
    emit("log", `Current theme: ${theme}`, "info");
  } catch (error) {
    emit("log", `Error getting theme: ${(error as Error).message}`, "error");
  }
};

const saveDataToFile = async () => {
  try {
    const data = {
      timestamp: new Date().toISOString(),
      message: "Export from Vue Sample Tool",
    };

    const filePath = await window.toolboxAPI.fileSystem.saveFile("vue-export.json", JSON.stringify(data, null, 2));

    if (filePath) {
      await showNotification("File Saved", `File saved to: ${filePath}`, "success");
      emit("log", `File saved to: ${filePath}`, "success");
    } else {
      emit("log", "File save cancelled", "info");
    }
  } catch (error) {
    emit("log", `Error saving file: ${(error as Error).message}`, "error");
  }
};
</script>

// templates/tool-templates/new/react-sample/src/components/ToolboxAPIDemo.tsx
import React, { useCallback } from "react";

interface ToolboxAPIDemoProps {
  onLog: (message: string, type?: "info" | "success" | "warning" | "error") => void;
}

export const ToolboxAPIDemo: React.FC<ToolboxAPIDemoProps> = ({ onLog }) => {
  const showNotification = useCallback(
    async (title: string, body: string, type: "success" | "info" | "warning" | "error") => {
      try {
        await window.toolboxAPI.utils.showNotification({
          title,
          body,
          type,
          duration: 3000,
        });
        onLog(`Notification shown: ${title} - ${body}`, type);
      } catch (error) {
        onLog(`Error showing notification: ${(error as Error).message}`, "error");
      }
    },
    [onLog],
  );

  const showLoading = useCallback(async () => {
    async function startLoading() {
      try {
        await window.toolboxAPI.utils.showLoading("Loading something for 3 seconds, please wait...");
        onLog("Loading indicator shown for 3 seconds", "info");

        setTimeout(async () => {
          try {
            await window.toolboxAPI.utils.hideLoading();
            onLog("Loading indicator hidden", "success");
          } catch (error) {
            onLog(`Error hiding loading: ${(error as Error).message}`, "error");
          }
        }, 3000);
      } catch (error) {
        onLog(`Error showing loading: ${(error as Error).message}`, "error");
      }
    }
    await startLoading();
  }, [onLog]);

  const copyToClipboard = useCallback(async () => {
    try {
      const data = {
        timestamp: new Date().toISOString(),
        message: "This data was copied from the React Sample Tool",
      };

      await window.toolboxAPI.utils.copyToClipboard(JSON.stringify(data, null, 2));
      await showNotification("Copied!", "Data copied to clipboard", "success");
    } catch (error) {
      onLog(`Error copying to clipboard: ${(error as Error).message}`, "error");
    }
  }, [onLog, showNotification]);

  const showCurrentTheme = useCallback(async () => {
    try {
      const theme = await window.toolboxAPI.utils.getCurrentTheme();
      await showNotification("Current Theme", `The current theme is: ${theme}`, "info");
      onLog(`Current theme: ${theme}`, "info");
    } catch (error) {
      onLog(`Error getting theme: ${(error as Error).message}`, "error");
    }
  }, [onLog, showNotification]);

  const saveDataToFile = useCallback(async () => {
    try {
      const data = {
        timestamp: new Date().toISOString(),
        message: "Export from React Sample Tool",
      };

      const filePath = await window.toolboxAPI.fileSystem.saveFile("react-export.json", JSON.stringify(data, null, 2));

      if (filePath) {
        await showNotification("File Saved", `File saved to: ${filePath}`, "success");
        onLog(`File saved to: ${filePath}`, "success");
      } else {
        onLog("File save cancelled", "info");
      }
    } catch (error) {
      onLog(`Error saving file: ${(error as Error).message}`, "error");
    }
  }, [onLog, showNotification]);

  return (
    <div className="card">
      <h2>🛠️ ToolBox API Examples</h2>

      <div className="example-group">
        <h3>Notifications</h3>
        <div className="button-group">
          <button
            onClick={() => showNotification("Success!", "Operation completed successfully", "success")}
            className="btn btn-success"
          >
            Show Success
          </button>
          <button
            onClick={() => showNotification("Information", "This is an informational message", "info")}
            className="btn btn-info"
          >
            Show Info
          </button>
          <button
            onClick={() => showNotification("Warning", "Please review this warning", "warning")}
            className="btn btn-warning"
          >
            Show Warning
          </button>
          <button onClick={() => showNotification("Error", "An error has occurred", "error")} className="btn btn-error">
            Show Error
          </button>

          <button onClick={() => showLoading()} className="btn btn-loading">
            Show Loading
          </button>
        </div>
      </div>

      <div className="example-group">
        <h3>Utilities</h3>
        <div className="button-group">
          <button onClick={copyToClipboard} className="btn">
            Copy to Clipboard
          </button>
          <button onClick={showCurrentTheme} className="btn">
            Get Theme
          </button>
          <button onClick={saveDataToFile} className="btn">
            Save File
          </button>
        </div>
      </div>
    </div>
  );
};
